import test from "node:test";
import assert from "node:assert/strict";
import { validateBegetOAuthNatSnapshot, validateBegetLegacyIptables,
  inspectBegetLegacyBackends } from
  "../scripts/release/inspect-beget-oauth-nat.mjs";

function fixture() {
  const ipv4 = `# Generated by iptables-save v1.8.10 (nf_tables)
*nat
:PREROUTING ACCEPT [12:720]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [12:720]
:POSTROUTING ACCEPT [12:720]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.18.0.0/16 ! -o br-3a38698ddffe -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER -i br-3a38698ddffe -j RETURN
-A DOCKER -d 127.0.0.1/32 ! -i br-3a38698ddffe -p tcp -m tcp --dport 5432 -j DNAT --to-destination 172.18.0.6:5432
-A DOCKER -d 127.0.0.1/32 ! -i br-3a38698ddffe -p tcp -m tcp --dport 5678 -j DNAT --to-destination 172.18.0.4:5678
-A DOCKER ! -i br-3a38698ddffe -p tcp -m tcp --dport 80 -j DNAT --to-destination 172.18.0.2:80
-A DOCKER ! -i br-3a38698ddffe -p tcp -m tcp --dport 443 -j DNAT --to-destination 172.18.0.2:443
COMMIT
`;
  const ipv6 = `*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d ::1/128 -m addrtype --dst-type LOCAL -j DOCKER
COMMIT
`;
  const nft = `table ip nat {
 chain DOCKER {
  ip daddr 127.0.0.1 tcp dport 5432 dnat to 172.18.0.6:5432
  ip daddr 127.0.0.1 tcp dport 5678 dnat to 172.18.0.4:5678
  tcp dport 80 dnat to 172.18.0.2:80
  tcp dport 443 dnat to 172.18.0.2:443
 }
}
table ip filter {
}
table ip6 nat {
}
table ip6 filter {
}
table ip raw {
}
`;
  const traefik = { Id: "a".repeat(64), Name: "/n8n-traefik-1",
    State: { Running: true }, NetworkSettings: { Networks: { n8n: {
      IPAddress: "172.18.0.2", NetworkID: "3a38698ddffe" + "b".repeat(52)
    } } } };
  return { ipv4, ipv6, nft, traefik };
}

test("OPS-07: pinned Docker NAT destinations resolve to the running Traefik container", () => {
  const { ipv4, ipv6, nft, traefik } = fixture();
  const report = validateBegetOAuthNatSnapshot(ipv4, ipv6, nft, traefik);
  assert.equal(report.ipv4Target, "172.18.0.2");
  assert.equal(report.ipv6Dnat, false);
});

test("OPS-07: alternate forwards, changed Traefik identity and nft native rules fail closed", () => {
  for (const change of [
    item => { item.ipv4 = item.ipv4.replace("172.18.0.2:443", "172.18.0.8:443"); },
    item => { item.ipv4 = item.ipv4.replace("COMMIT", "-A DOCKER -p tcp --dport 8791 -j DNAT --to-destination 172.18.0.1:8791\nCOMMIT"); },
    item => { item.ipv6 = item.ipv6.replace("COMMIT", "-A DOCKER -p tcp --dport 443 -j REDIRECT --to-ports 8791\nCOMMIT"); },
    item => { item.traefik.NetworkSettings.Networks.n8n.IPAddress = "172.18.0.8"; },
    item => { item.traefik.NetworkSettings.Networks.n8n.NetworkID = "f".repeat(64); },
    item => { item.nft = item.nft.replace("172.18.0.6:5432", "172.18.0.9:5432"); },
    item => { item.nft += "table inet shadow {\n}\n"; },
    item => { item.nft = item.nft.replace("table ip raw", "table ip raw {\n redirect to :8791\n}\ntable ip raw"); }
  ]) {
    const item = fixture();
    change(item);
    assert.throws(() => validateBegetOAuthNatSnapshot(
      item.ipv4, item.ipv6, item.nft, item.traefik), /NAT inventory/);
  }
});

test("OPS-07: a second iptables backend cannot introduce alternate NAT or TPROXY", () => {
  const empty = "# Generated by iptables-save\n*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n";
  assert.equal(validateBegetLegacyIptables(empty, ""), true);
  for (const extra of [
    "-A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 127.0.0.1:8789",
    "-A PREROUTING -p tcp --dport 443 -j TPROXY --on-port 8789"
  ]) {
    assert.throws(() => validateBegetLegacyIptables(empty + extra + "\n", ""),
      /legacy iptables contains a rule/);
  }
  assert.throws(() => validateBegetLegacyIptables("*nat\n:DOCKER - [0:0]\n", ""),
    /incomplete table/);
});

test("OPS-07: absent legacy backend is not initialized; present backend cannot modprobe", async () => {
  const called = [];
  const stat = async path => {
    called.push(path);
    if (path.endsWith("/ip6_tables_names")) throw Object.assign(new Error("absent"), { code: "ENOENT" });
  };
  const run = async (binary, args) => {
    called.push([binary, ...args]);
    return { stdout: "*nat\n:PREROUTING ACCEPT [0:0]\nCOMMIT\n" };
  };
  assert.equal(await inspectBegetLegacyBackends({ stat, run }), true);
  assert.deepEqual(called, ["/proc/net/ip_tables_names",
    ["iptables-legacy-save", "-M", "/bin/false"], "/proc/net/ip6_tables_names"]);
  await assert.rejects(inspectBegetLegacyBackends({ stat: async () => {},
    run: async () => ({ stdout: "*mangle\n-A PREROUTING -j TPROXY\nCOMMIT\n" }) }),
  /legacy iptables contains a rule/);
});
